/**
 * videoMap.js — Maps ISL gloss tokens to their .mp4 video paths.
 *
 * All paths are relative to the React /public folder.
 * Add or remove entries here as you add video files to public/signs/.
 *
 * Tokens NOT present in this map are silently skipped during playback
 * without breaking the sequence.
 */

const videoMap = {
  // ── Pronouns ───────────────────────────────────────────────────────────────
  ME:          "/signs/ME.mp4",
  MY:          "/signs/MY.mp4",
  WE:          "/signs/WE.mp4",
  OUR:         "/signs/OUR.mp4",
  YOU:         "/signs/YOU.mp4",
  YOUR:        "/signs/YOUR.mp4",
  HE:          "/signs/HE.mp4",
  SHE:         "/signs/SHE.mp4",
  THEY:        "/signs/THEY.mp4",
  IT:          "/signs/IT.mp4",
  THIS:        "/signs/THIS.mp4",
  THAT:        "/signs/THAT.mp4",

  // ── Common verbs ───────────────────────────────────────────────────────────
  GO:          "/signs/GO.mp4",
  COME:        "/signs/COME.mp4",
  EAT:         "/signs/EAT.mp4",
  DRINK:       "/signs/DRINK.mp4",
  SLEEP:       "/signs/SLEEP.mp4",
  WALK:        "/signs/WALK.mp4",
  RUN:         "/signs/RUN.mp4",
  READ:        "/signs/READ.mp4",
  WRITE:       "/signs/WRITE.mp4",
  STUDY:       "/signs/STUDY.mp4",
  WORK:        "/signs/WORK.mp4",
  PLAY:        "/signs/PLAY.mp4",
  LEARN:       "/signs/LEARN.mp4",
  TEACH:       "/signs/TEACH.mp4",
  HELP:        "/signs/HELP.mp4",
  WANT:        "/signs/WANT.mp4",
  NEED:        "/signs/NEED.mp4",
  LIKE:        "/signs/LIKE.mp4",
  LOVE:        "/signs/LOVE.mp4",
  KNOW:        "/signs/KNOW.mp4",
  THINK:       "/signs/THINK.mp4",
  FEEL:        "/signs/FEEL.mp4",
  SEE:         "/signs/SEE.mp4",
  HEAR:        "/signs/HEAR.mp4",
  SPEAK:       "/signs/SPEAK.mp4",
  TELL:        "/signs/TELL.mp4",
  ASK:         "/signs/ASK.mp4",
  GIVE:        "/signs/GIVE.mp4",
  TAKE:        "/signs/TAKE.mp4",
  BUY:         "/signs/BUY.mp4",
  CALL:        "/signs/CALL.mp4",
  WATCH:       "/signs/WATCH.mp4",
  MEET:        "/signs/MEET.mp4",
  HAVE:        "/signs/HAVE.mp4",
  MAKE:        "/signs/MAKE.mp4",
  SHOW:        "/signs/SHOW.mp4",
  REMEMBER:    "/signs/REMEMBER.mp4",
  UNDERSTAND:  "/signs/UNDERSTAND.mp4",
  WAIT:        "/signs/WAIT.mp4",
  SIT:         "/signs/SIT.mp4",
  STAND:       "/signs/STAND.mp4",
  STOP:        "/signs/STOP.mp4",
  START:       "/signs/START.mp4",
  FINISH:      "/signs/FINISH.mp4",
  OPEN:        "/signs/OPEN.mp4",
  CLOSE:       "/signs/CLOSE.mp4",
  PUT:         "/signs/PUT.mp4",
  BRING:       "/signs/BRING.mp4",
  FORGET:      "/signs/FORGET.mp4",
  LIVE:        "/signs/LIVE.mp4",

  // ── Places ─────────────────────────────────────────────────────────────────
  SCHOOL:      "/signs/SCHOOL.mp4",
  HOME:        "/signs/HOME.mp4",
  HOUSE:       "/signs/HOUSE.mp4",
  HOSPITAL:    "/signs/HOSPITAL.mp4",
  MARKET:      "/signs/MARKET.mp4",
  PARK:        "/signs/PARK.mp4",
  OFFICE:      "/signs/OFFICE.mp4",
  COLLEGE:     "/signs/COLLEGE.mp4",
  INDIA:       "/signs/INDIA.mp4",
  TEMPLE:      "/signs/TEMPLE.mp4",
  STATION:     "/signs/STATION.mp4",
  AIRPORT:     "/signs/AIRPORT.mp4",
  SHOP:        "/signs/SHOP.mp4",
  HOTEL:       "/signs/HOTEL.mp4",
  BANK:        "/signs/BANK.mp4",
  LIBRARY:     "/signs/LIBRARY.mp4",

  // ── Objects ────────────────────────────────────────────────────────────────
  FOOD:        "/signs/FOOD.mp4",
  WATER:       "/signs/WATER.mp4",
  MILK:        "/signs/MILK.mp4",
  RICE:        "/signs/RICE.mp4",
  BREAD:       "/signs/BREAD.mp4",
  BOOK:        "/signs/BOOK.mp4",
  PEN:         "/signs/PEN.mp4",
  MONEY:       "/signs/MONEY.mp4",
  PHONE:       "/signs/PHONE.mp4",
  COMPUTER:    "/signs/COMPUTER.mp4",
  CAR:         "/signs/CAR.mp4",
  BUS:         "/signs/BUS.mp4",
  TRAIN:       "/signs/TRAIN.mp4",
  BAG:         "/signs/BAG.mp4",
  CLOTHES:     "/signs/CLOTHES.mp4",
  MEDICINE:    "/signs/MEDICINE.mp4",

  // ── Descriptors ────────────────────────────────────────────────────────────
  GOOD:        "/signs/GOOD.mp4",
  BAD:         "/signs/BAD.mp4",
  HAPPY:       "/signs/HAPPY.mp4",
  SAD:         "/signs/SAD.mp4",
  SICK:        "/signs/SICK.mp4",
  BIG:         "/signs/BIG.mp4",
  SMALL:       "/signs/SMALL.mp4",
  FAST:        "/signs/FAST.mp4",
  SLOW:        "/signs/SLOW.mp4",
  HOT:         "/signs/HOT.mp4",
  COLD:        "/signs/COLD.mp4",
  NEW:         "/signs/NEW.mp4",
  OLD:         "/signs/OLD.mp4",
  BEAUTIFUL:   "/signs/BEAUTIFUL.mp4",
  CLEAN:       "/signs/CLEAN.mp4",
  IMPORTANT:   "/signs/IMPORTANT.mp4",
  SAFE:        "/signs/SAFE.mp4",
  DANGER:      "/signs/DANGER.mp4",
  READY:       "/signs/READY.mp4",
  FREE:        "/signs/FREE.mp4",

  // ── Time ───────────────────────────────────────────────────────────────────
  TODAY:       "/signs/TODAY.mp4",
  TOMORROW:    "/signs/TOMORROW.mp4",
  YESTERDAY:   "/signs/YESTERDAY.mp4",
  NOW:         "/signs/NOW.mp4",
  MORNING:     "/signs/MORNING.mp4",
  NIGHT:       "/signs/NIGHT.mp4",
  LATER:       "/signs/LATER.mp4",
  SOON:        "/signs/SOON.mp4",
  ALREADY:     "/signs/ALREADY.mp4",
  ALWAYS:      "/signs/ALWAYS.mp4",
  NEVER:       "/signs/NEVER.mp4",
  DAY:         "/signs/DAY.mp4",
  WEEK:        "/signs/WEEK.mp4",
  MONTH:       "/signs/MONTH.mp4",
  YEAR:        "/signs/YEAR.mp4",

  // ── Questions ──────────────────────────────────────────────────────────────
  WHERE:       "/signs/WHERE.mp4",
  WHAT:        "/signs/WHAT.mp4",
  WHEN:        "/signs/WHEN.mp4",
  WHO:         "/signs/WHO.mp4",
  WHY:         "/signs/WHY.mp4",
  HOW:         "/signs/HOW.mp4",
  WHICH:       "/signs/WHICH.mp4",

  // ── Negation ───────────────────────────────────────────────────────────────
  NO:          "/signs/NO.mp4",
  NOTHING:     "/signs/NOTHING.mp4",
  NOBODY:      "/signs/NOBODY.mp4",

  // ── Social / greetings ─────────────────────────────────────────────────────
  HELLO:       "/signs/HELLO.mp4",
  BYE:         "/signs/BYE.mp4",
  "THANK-YOU": "/signs/THANK-YOU.mp4",
  SORRY:       "/signs/SORRY.mp4",
  PLEASE:      "/signs/PLEASE.mp4",
  YES:         "/signs/YES.mp4",
  WELCOME:     "/signs/WELCOME.mp4",

  // ── People / family ────────────────────────────────────────────────────────
  FRIEND:      "/signs/FRIEND.mp4",
  FAMILY:      "/signs/FAMILY.mp4",
  FATHER:      "/signs/FATHER.mp4",
  MOTHER:      "/signs/MOTHER.mp4",
  BROTHER:     "/signs/BROTHER.mp4",
  SISTER:      "/signs/SISTER.mp4",
  TEACHER:     "/signs/TEACHER.mp4",
  STUDENT:     "/signs/STUDENT.mp4",
  DOCTOR:      "/signs/DOCTOR.mp4",
  POLICE:      "/signs/POLICE.mp4",

  // ── Emergency ──────────────────────────────────────────────────────────────
  HELP:        "/signs/HELP.mp4",
  PAIN:        "/signs/PAIN.mp4",
  EMERGENCY:   "/signs/EMERGENCY.mp4",
  NAME:        "/signs/NAME.mp4",
};

export default videoMap;